name: Generate Topic Content

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday
  workflow_dispatch:

permissions:
  contents: write  # Ensure that the action can push to the repository
  pull-requests: write

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Latest version compatible with Node.js 20
        with:
          python-version: '3.9'

      - name: Install Required Packages
        run: |
          pip install transformers markdownify
          # Install either TensorFlow or PyTorch
          pip install torch  # This installs PyTorch
          # Or, for TensorFlow, uncomment the next line
          # pip install tensorflow

      - name: Set Environment Variables
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV

      - name: Generate Tutorial
        run: |
          python generate_gemini.py  # Assuming your script is named generate_gemini.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4  # Ensure this is the latest version
        with:
          title: "Notes generated for ${{ env.MARKDOWN_FILENAME }}"
          body: "This PR contains a generated notes."
          base: main
          branch: topic-update
          commit-message: "Totorials generated and file created ${{ env.MARKDOWN_FILENAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
